### ISSUE TITLE
rework connection manager

### ISSUE THREAD

**Issue by mispp** [mispp/goat#13]
connection management needs to be reworked. goal here is to implement behavior similar to mssql management studio. this means:
- every tab can have a different connection to different database (tab1-> mysql, tab2->postgres, tab3->mssql).
- each tab should be easily identifiable which connection is used 
- each tab should easily switch connection it is using
- long running query in one tab must not affect other tabs

Therefore,
- connection manager dialog should be brought back and establishing connection should be handled through it, optional toolbar/treeview control should be added to display established connection
- menu list of established connections should be added
- disconnecting should be done based on a list of established connections shown in mentioned tree view control 
- mentioned treeview control would later be used also to view objects in databases (e.g. list tables, then for each table list columns; list users; etc.)
- to be able to easily identify which connection is used dropbox and execute button(s) should be brought back into the tab itself

**Comment by mispp** [comment]
@asw-dev can't really tell which tab is using which connection, but i'd assume the one selected on top. having the control in the tab should imo work better.

**Comment by mispp** [comment]
with connection manager like this we can't simply use controls like listview, treeview to track active connections (basically to use a model behind a control). not sure if singleton approach is good (probably not), but having pointer instead of local variable to connection manager as done now can be used to make models and connect them to list views easily. or there is a better way to handle this? to be honest i'm kinda in favor of using models since connection to guis become trivial.

anyhow, reference on how to handle this should be based on these screenshots:
- [heidi sql](https://www.heidisql.com/images/screenshots/query.png)
- same is for [mssql server management studio](https://www.brentozar.com/wp-content/uploads/2015/07/SSMS-Update-Available.png)

besides tree view examples, most of the tools on the market use connection manager dialog (with mssql being an exception, it's a bit different, but still a dialog). to keep the tool somehow aligned with the ones established on the market, i'd like to replace current implementation and do it as originally meant. for this we'd need change connection manager again to allocate items on the heap and use it as subclass of QStandardItem.

[something like this would be the ultimate goal] (https://www.heidisql.com/images/screenshots/connection.png).

Any suggestions?

**Comment by mispp** [comment]
Playing around with main window:
- considering that we now have wide screen monitors, move toolbar to left / vertical orientation
- added object browser
- action (execute query) bundled with the tab
- information about which connection is used is also bundled with the tab
- left all the buttons on the vertical for graphics, but all of them except the new/open/save and connection manager (one button) shuld be removed

@asw-dev opinions? i think this is the best way to use screen realestate

![image](https://user-images.githubusercontent.com/6314582/43655952-fd7efc46-9750-11e8-8224-e88a60ea5ab0.png)

**Comment by asw-dev** [comment]
The layout is nice, and appears usable, personally I'd move the object browser right of the buttons (perhaps in the long term you could drag and dock it where you please). I'm not much of a gui guy so I can't push my opinions too hard.

I had a very different set of goals & target in mind as I was designing my branch. I'll let you know what I was thinking, but you should go with want you like. 

The goal was to keep things as simple as possible. Both from code and a user's perspective. Code so I can get a working app to dog food right away, and user because I don't need that many bells and whistles to clutter my workflow (I barely use ssms's object browser at all and would rather query sys tables for the info). As the app / my needs grew I could change it later.

That in mind I didn't plan to have a connection manager at all, or in other words the main window is the connection manager. What you see in the connection combo is all there is. This eliminates the need for another dialog / model that holds the connections. One off connections and simple edits can use the single-connection dialog, and bulk edits are done by `vi ~/.config/goat/connections.ini`

This however is not enough for even me, as you need a way to have connection per tab, and IMO a way to share a connection for every tab. Both use cases are common as I am either working with the same queries on 2 databases (want the connection selection locked to global), or am working on different queries (unlocked).

To do this I was planning on:

- add an online / offline icon in the connection combo
- having each tab track which connection was last used / is currently using
- display the on a bottom toolbar (along with other info like rows returned, elapsed time, etc.)
- have 1 new button that locks/unlocks the connection selection. Only when unlocked would switching a tab change the connection to what the tab last used

Like or not, I imagine you can see how this would only require minimal changes to implement.

If you want to head this way there is a asw-dev branch on my repo this up to date minus the manager and tab ui changes.

**Comment by mispp** [comment]
> I'd move the object browser right of the buttons 

it's implemented as a dock widget, so it can be moved.

> add an online / offline icon in the connection combo

this might be resolved by using a convention: combobox should only display open connections. all connection should be in connection manager dialog. 

> having each tab track which connection was last used / is currently using

this is how it was originally working: connection manager class was a singleton. it provided a model that combobox from the tab was linked to. whenever you'd run a query in a tab, it would check which connection is in the combobox and run against that one. one important convention: combobox showed only *open* connections. this is something like with browsers: address bar which is specific to content of that tab is below the tab itself. it's more intuitive and it bundles together things that go together.

> display the on a bottom toolbar (along with other info like rows returned, elapsed time, etc.)

this was written in 'messages' tab, i guess it shouldn't be difficult to add it to status bar.

`ui->resultsText->appendPlainText("Number of rows affected: " + QString::number(q.numRowsAffected()));`

what i'd like to see in the end is: 
- connection manager dialog like ti was before, basically editor for connections.ini and the thing that will open a connection
- each tab has a combobox so we know which connection is used in each tab, this combobox should display only open connections
- execute button (and additionally stop button) should also be in the tab, so it can be enabled/disabled based on the execution status. for me it would make more sense like this since we avoid synchronization between what buttons are enabled/disabled on the main tool bar based on which tab got selected AND execution status. if they are in a tab, buttons are linked only to the state of query execution.
- maybe a dynamic menu (i.e. when clicked on 'connection' menu, you get a list of available connections in that list).

if this somehow fits into what you had in mind, i'd merge it and then work on steering it in direction what was just described.

**Comment by asw-dev** [comment]
> execute button (and additionally stop button) should also be in the tab ... since we avoid synchronization between what buttons
Unless you plan to move / remove the connection menu you will still need to update their enabled state when you change tabs. Doing a dynamic menu would avoid this, but then the user can't see what the shortcut keys are from the menu, and would need to go to the documentation. I don't think you need to be too worried about syncing, just have a slot that applies the state of the ui and hook all events through it (not the most efficient, but being as close to stateless is a good design).

> singleton
Try to avoid singletons (they are a bit of an anti-pattern). Every single instance class in a gui program like this one can be owned by the main window and have it's pointer passed to who needs it. Otherwise you will have to removed to call destroy methods instead of using destructors, and can't use them without locking / single threading in unit tests (if we ever get to that point).

Other than that, sounds good to me.

**Comment by mispp** [comment]
> Try to avoid singletons (they are a bit of an anti-pattern)

i read that there is a problem with multithreading with singletons, but it's far beyond my level of c++, so i cant say if that would cause issues here.

> I don't think you need to be too worried about syncing

it's not only this. i mean, i am worried about how to hook this whole thing up (not being a c++ developer i'm having obvious issues with app design), but it's also about gui simplicity and intuitivity. i kinda stick to what works elsewhere, like browser example to make it somehow 'familiar'.

> Every single instance class in a gui program like this one can be owned by the main window and have it's pointer passed to who needs it. 

i would like to have one instance of a class per program that would manage connections and it needs to be accessible in followup components. so far singleton seemd like ok-ish solution to the problem... but if singleton is not ok and your proposal works - great. we can do it like that.

**Comment by mispp** [comment]
outdated

open connections disconnect actions are available as toolbutton on main toolbar
